config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'searches#show'

  resource :search, only: [:show, :create]

  resources :tickets, only: [:show, :create, :destroy] do
    collection do
      get :my
      post :buy
    end
  end

  namespace :admin do

    resources :railway_stations do
      patch :update_station_place_in_route, on: :member
    end

    resources :routes
    resources :tickets, except: [:new, :create]

    resources :trains do
      resources :carriages, shallow: true
    end

  end 

  

end

app/models/route.rb
class Route < ActiveRecord::Base
  has_many :trains
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes

  validates :name, presence: true
  validate :stations_count

  before_validation :set_name
  before_create :order_stations

  private

  def set_name
    if railway_stations.size > 1
      self.name = "#{railway_stations.first.title} - #{railway_stations.last.title}"
    end
  end

  def order_stations
    railway_stations_routes.each_with_index do |station, position|
      station.position = position
    end
  end

  def stations_count
    errors.add(:base, 'Route should contain at least 2 stations') if railway_stations.size < 2
  end
end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseController
before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all 
  end

  def show
  end

  def new
    @route = Route.new
  end

  def edit
  end

  def create
    @route = Route.new(route_params)
    if @route.save
      redirect_to admin_route_path(@route), notice: t('.notice')
    else
      render :new
    end
  end

  def update
    if @route.update(route_params)
      redirect_to admin_route_path(@route), notice: t('.notice')
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to admin_routes_path, notice: t('.notice')
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name, railway_station_ids: [])
  end
end

app/controllers/routes.rb
class RoutesController < ApplicationController
before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all 
  end

  def show
  end

  def new
    @route = Route.new
  end

  def edit
  end

  def create
    @route = Route.new
    if @route.save
      redirect_to @route, notice: 'Route was successfully created.'
    else
      render :new
    end
  end

  def update
    if @route.update(route_params)
      redirect_to @route, notice: 'Route was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to routes_path, notice: 'Route was successfully deleted.'
  end

  private

  def route_params
    params.require(:route).permit(:name)
  end

  def set_route
    @route = Route.find(params[:id])
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all 
  end

  def show
  end

  def new
    @route = Route.new
  end

  def edit
  end

  def create
    @route = Route.new(route_params)
    if @route.save
      redirect_to @route, notice: 'Route was successfully created.'
    else
      render :new
    end
  end

  def update
    if @route.update(route_params)
      redirect_to @route, notice: 'Route was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to routes_path, notice: 'Route was successfully deleted.'
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name, railway_station_ids: [])
  end
end

app/views/admin/routes/_form.html.erb
<%= render 'shared/errors_messages', resource: @route %>

<%= form_for [:admin, @route] do |f| %>
  
<div class="card">
    <h3 class="card-header primary-color white-text"><i class="fa fa-road" aria-hidden="true"></i> </h3>

    <div class="card-block">
        <div class="col-md-6">
            <%= f.collection_select :railway_station_ids, RailwayStation.all.ordered_by_title, :id, :title, {}, { multiple: true, class: "mdb-select colorful-select " } %>

            <div class="center-on-small-only">
                <button type="submit" class="btn btn-primary"><%= t('.submit', action: @route.new_record? ? 'Создать' : 'Изменить') %></button>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/admin/routes/_route.html.erb
<tr>
  <td><%= route.name %></td>
  <%= render 'shared/actions', links: {
                show: admin_route_path(route),
                edit: edit_admin_route_path(route),
                delete: admin_route_path(route)
                } %>
</tr>

app/views/admin/routes/_stations.html.erb
<br />
<!-- Horizontal Steppers -->
<div class="row">
    <div class="col-md-12">
        <!-- Stepers Wrapper -->
        <ul class="stepper stepper-horizontal">
        <% stations.each do |station| %>
        <li class="completed">
        <a href="<%= admin_railway_station_path(station) %>">
                    <span class="circle" ><%= station.within_route(@route, :position) %></span>
                    <span class="label"><%=  station.title %></span>
                </a>
            </li>
            <% end %>
        </ul>
        <!-- /.Stepers Wrapper -->
    </div>
</div>
<!-- /.Horizontal Steppers -->
<br />

<div class="card">
    <h3 class="card-header primary-color white-text"><i class="fa fa-calendar" aria-hidden="true"></i> <%= t('admin.routes.attributes.stations') %>:</h3>

    <div class="card-block">

        <br />

        <table class="table table-hover">
            <thead>
                <tr>
                    <th class="text-left"><%= t('admin.railway_stations.attributes.title') %></th>
                    <th class="text-center"><%= t('admin.railway_stations.attributes.position') %></th>
                    <th class="text-center"><%= t('admin.railway_stations.attributes.arrival') %></th>
                    <th class="text-center"><%= t('admin.railway_stations.attributes.departure') %></th>
                    <th class="text-center"><%= t('shared.actions') %></th>
                </tr>
            </thead>
            <tbody>
                <% stations.each do |station| %>
                    <tr>
                        <td class="align-middle">
                            <%= link_to station.title, admin_railway_station_path(station) %>
                        </td>
                      
                        <%= form_tag(update_station_place_in_route_admin_railway_station_path(station), method: :patch) do %>
                            <%= hidden_field_tag :route_id, @route.id %>
                            <div class="row">
                                <td class="align-bottom"> 
                                    <div class="range-field"> 
                                        <%= range_field_tag :position, station.within_route(@route, :position) %>
                                    </div>
                                </td>
                                <td class="align-bottom"> 
                                    <%= time_field_tag :arrival_time, station.within_route(@route, :arrival_time), placeholder: t('admin.railway_stations.attributes.arrival_time'), class: 'form-control', style: "width:80px;" %>
                                </td>
                                <td> 
                                    <%= time_field_tag :departure_time, station.within_route(@route, :departure_time), placeholder: t('admin.railway_stations.attributes.departure_time'), class: 'form-control' %>
                                </td>
                               
                                <td class="text-center"> 
                                    <button type="submit" class="btn btn-outline-primary waves-effect"><%= t('shared.update') %></button>
                                </td>
                            </div>  
                        <% end %>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div> 

app/views/admin/routes/edit.html.erb
<div class="divider-new">
    <h2 class="h2-responsive">
        <%= t('.title') %> <strong> <span class="text-muted"></span></strong>
    </h2>
</div>

<%= render 'form' %>

<br>

<%= link_to t('shared.back'), admin_routes_path, class: "text-danger" %> |
<%= link_to t('shared.show'), admin_route_path(@route), class: "text-danger" %> 

app/views/admin/routes/index.html.erb
<div class="divider-new">
    <h2 class="h2-responsive">
        <%= t('.title') %> <strong> <span class="text-muted"></span></strong>
    </h2>
</div>

<div class="card">
    <h3 class="card-header primary-color white-text"><i class="fa fa-road" aria-hidden="true"></i> <%= t('.title') %>:</h3>

    <div class="card-block">

        <div class="row">
            <div class="col-md-12">
                <p class="text-right">
                    <span class=""> <%= link_to t('shared.add'), new_admin_route_path,
                          class: 'btn btn-secondary', role: 'button' %>
                    </span>
                </p>
            </div>
        </div>

        <table class="table text-center table-hover">
            <thead class="text-center">
                <tr>
                    <th class="text-center"><%= t('admin.routes.attributes.name') %></th>
                    <th class="text-center"><%= t('shared.actions') %></th>
                </tr>
            </thead>

            <tbody>
                <%= render @routes %>
            </tbody>
        </table>
    </div>
</div>

<br />

<%= link_to t('shared.back'), :back, class: "text-danger" %>

app/views/admin/routes/new.html.erb
<div class="divider-new">
    <h2 class="h2-responsive">
        <%= t('.title') %> <strong> <span class="text-muted"></span></strong>
    </h2>
</div>

<%= render 'form' %>

<br>

<%= link_to t('shared.back'), admin_routes_path, class: "text-danger" %>

app/views/admin/routes/show.html.erb
<div class="divider-new">
    <h2 class="h2-responsive">
        <%= t('.title') %> <strong> <span class="text-muted">"<%= @route.name %>"</span></strong>
    </h2>
</div>

<h4 class="text-center text-muted"><%= t('admin.routes.attributes.route_map') %>:</h4>

<div>
  <%= render 'stations', stations: @route.railway_stations.ordered %>
</div>
<br />

<h4 class="text-center text-muted"><%= t('admin.routes.attributes.trains') %>:</h4>



<div>
    <% if @route.trains.present? %>
        <ul>
            <% @route.trains.each do |train| %>
                <li>
                    <%= link_to admin_train_path(train) do %>
                        <span><i class="fa fa-subway" aria-hidden="true"></i> <%= train.number %></span>
                    <% end %>
                </li>
            <% end %>
        </ul>
    <% else %>
        <%= t('shared.empty') %>
    <% end %>
</div>

<hr>

<%= link_to t('shared.back'), admin_routes_path, class: "text-danger" %> |
<%= link_to t('shared.edit'), edit_admin_route_path(@route), class: "text-danger" %> 
<br />