config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'searches#show'

  resource :search, only: [:show, :create]

  resources :tickets, only: [:show, :create, :destroy] do
    collection do
      get :my
      post :buy
    end
  end

  namespace :admin do

    resources :railway_stations do
      patch :update_station_place_in_route, on: :member
    end

    resources :routes
    resources :tickets, except: [:new, :create]

    resources :trains do
      resources :carriages, shallow: true
    end

  end 

  

end

app/models/train.rb
class Train < ActiveRecord::Base
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :route
  has_many :tickets
  has_many :carriages

  validates :number, presence: true

  def capacity_by_type(carriage_type, seat_type)
    Carriage.where(type: carriage_type).sum(seat_type) || 0
  end

  def ordered_carriages
    order_from_tail ? carriages.ordered.reverse_order : carriages.ordered
  end
end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end
 
  def edit
  end

  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to admin_train_path(@train), notice: t('.notice')
    else
      render :new
    end
  end

  def update
    if @train.update(train_params)
      redirect_to admin_train_path(@train), notice: t('.notice')
    else
      render :edit
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    redirect_to admin_trains_path, notice: t('.notice')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:number, :current_station_id, :route_id, :order_from_tail)
    end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end
 
  def edit
  end

  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to @train, notice: 'Train was successfully created.'
    else
      render :new
    end
  end

  def update
    if @train.update(train_params)
      redirect_to @train, notice: 'Train was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    redirect_to trains_url, notice: 'Train was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:number, :current_station_id, :route_id, :order_from_tail)
    end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/trains/_form.html.erb
<%= form_for(@train) do |f| %>
  <%= render 'shared/errors_messages', resource: @train %>

  <div class="field">
    <%= f.label :number %>
    <%= f.text_field :number %>
  </div>

  <br />

  <%= f.select :current_station_id, RailwayStation.all.map{ |station| [ "#{station.title}", station.id ] }, {prompt: "Select station"}, class: "mdb-select colorful-select dropdown-warning" %>

  <%= f.select :route_id, Route.all.map{ |route| [ "#{route.name}", route.id ] }, {prompt: "Select route"}, class: "mdb-select colorful-select dropdown-warning" %>

   <div class="field">
      
      <%= f.check_box :order_from_tail %>
      <%= f.label :order_from_tail %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trains</h1>

<table class="table text-center table-hover">
  <thead class="table-inverse text-center">
    <tr>
      <th class="text-center">Number</th>
      <th class="text-center">Route</th>
      <th class="text-center">Current station</th>
      <th class="text-center" colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to 'New Train', new_train_path %> |
<%= link_to 'Back', root_path %>

app/views/trains/new.html.erb
<h1>New Train</h1>

<%= render 'form' %>

<%= link_to 'Back', trains_path %>

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @train.number %>
</p>

<p>
  <strong>Currnet Station</strong>
  <% if @train.current_station.present? %>
      <%= link_to @train.current_station.title, @train.current_station %>
  <% else %>
      Current station isn't set
  <% end %>
</p>

<p>
  <strong>Route:</strong>
  <% if @train.route.present? %>
      <%= link_to @train.route.name, @train.route %>
  <% else %>
      Route isn't set
  <% end %>
</p>


<h2>Carriages:</h2>
<div>
  <span><%= link_to 'Add carriage', new_train_carriage_path(@train) %></p></span>
  <table class="table">
    <thead>
    <tr>
      <th>Number</th>
      <th>Type</th>
      <th>Seats</th>
      <th colspan="3">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @train.ordered_carriages.each do |carriage| %>
        <tr>
          <td><%= link_to carriage.number, carriage_path(carriage) %></td>
          <td><%= carriage.type_label %></td>
          <td><%= render "carriages/seats_#{carriage.type.underscore}", carriage: carriage %></td>
          <td><%= link_to 'Show', carriage_path(carriage) %></td>
          <td><%= link_to 'Edit', edit_carriage_path(carriage) %></td>
          <td><%= link_to 'Destroy', carriage_path(carriage), method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

<h2>Seats count by type:</h2>
<table class="table">
  <thead>
  <tr>
    <th>Carriage type</th>
    <th>Seat type</th>
    <th>Count</th>
  </tr>
  </thead>
  <tbody>
    <% Carriage::TYPES.each do |carriage_type, carriage_label| %>
      <% Carriage::SEATS_TYPES.each do |seats_type, seats_label| %>
          <% count = @train.capacity_by_type(carriage_type, seats_type) %>
          <% if count > 0 %>
            <tr>
              <td><%= carriage_label %></td>
              <td><%= seats_label %></td>
              <td><%= count %></td>
            </tr>
          <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_train_path(@train) %> |
<%= link_to 'Back', trains_path %>