config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'searches#show'

  resource :search, only: [:show, :create]

  resources :tickets, only: [:show, :create, :destroy] do
    collection do
      get :my
      post :buy
    end
  end

  namespace :admin do

    resources :railway_stations do
      patch :update_station_place_in_route, on: :member
    end

    resources :routes
    resources :tickets, except: [:new, :create]

    resources :trains do
      resources :carriages, shallow: true
    end

  end 

  

end

app/views/shared/_actions.html.erb
<td class="">
    <% if links.key?(:show) %>
        <%= link_to(links[:show], data: {toggle: 'tooltip', title: t('shared.show')}) do %>
            <i class="fa fa-eye"></i>
        <% end %>
    <% end %>
    <% if links.key?(:edit) %>
        <%= link_to(links[:edit], data: {toggle: 'tooltip', title: t('shared.edit')}) do %>
              <span class="green-text"><i class="fa fa-pencil"></i></span>
        <% end %>
    <% end %>
    <% if links.key?(:delete) %>
        <%= link_to(links[:delete], method: :delete, data: {toggle: 'tooltip', title: t('shared.destroy'), confirm: t('shared.confirm')}) do %>
              <span class="red-text"><i class="fa fa-times"></i></span>
        <% end %>
    <% end %>
</td> 

app/views/shared/_errors_messages.html.erb
<div data-alert class="alert-box">
  <script type="text/javascript">
        <% if resource.errors.any? %>
            <% resource.errors.full_messages.each do |msg| %>
                toastr.error('<%= msg %>')
            <% end %>
        <% end %>
    </script>
  
</div>

app/views/shared/_nav_bar.html.erb
  <!--Navbar-->
        <nav class="navbar fixed-top navbar-toggleable-md scrolling-navbar navbar-dark double-nav">
        <% if user_signed_in? && current_user.admin? %>
            <!-- SideNav slide-out button -->
            <div class="float-left">
                <a href="#" data-activates="slide-out" class="button-collapse"><i class="fa fa-bars"></i></a>
            </div>
            <% end %>

            <!-- Breadcrumb-->
            <div class="breadcrumb-dn mr-auto">
                <p><strong><i class="fa fa-subway red-text"> </i>  Tutu</strong></p>
            </div>
            <% if user_signed_in? %> 
          <ul class="navbar-nav ml-auto nav-flex-icons">
                          <li class="nav-item">
                              <a class="nav-link" href="<%= root_path %>"><i class="fa fa-home"> </i><span class="hidden-sm-down"> <%= t('.home_page') %> </span></a>
                          </li>
                          <li class="nav-item">
                              <a class="nav-link" href="<%= my_tickets_path%>"><i class="fa fa-ticket"> </i><span class="hidden-sm-down"> <%= t('.my_tickets') %> </span></a>
                          </li>
                          <li class="nav-item">
                              <a class="nav-link" href="<%= edit_user_registration_path %>"><i class="fa fa-user"> </i><span class="hidden-sm-down">  <%= "#{current_user.full_name}" %> </span></a>
                          </li>
                          <li class="nav-item">
                              <%= link_to destroy_user_session_path, method: :get, rel: "nofollow", class: "nav-link" do %>
                                    <span class="hidden-sm-down "> <i class="fa fa-sign-out"> </i> <%= t('.log_out') %></span>
                              <% end %>
                          </li>
                      </ul>
                  <% else %>
                      <ul class="navbar-nav ml-auto nav-flex-icons">
                          <li class="nav-item">
                              <a class="nav-link" href="<%= new_user_session_path %>" rel="nofollow"><i class="fa fa-sign-in"></i> <span class="hidden-sm-down"><%= t('.log_in') %></span></a>
                          </li> 
                          <li class="nav-item">
                              <a class="nav-link" href="<%= new_user_registration_path%>" rel="nofollow"><i class="fa fa-user-plus"></i> <span class="hidden-sm-down"><%= t('.sign_up') %></span></a>
                          </li> 
                      </ul>

                  <% end %>
        </nav>
        <!--/.Navbar-->

app/views/shared/_sidebar.html.erb
 <!-- Sidebar navigation -->
        <ul id="slide-out" class="side-nav fixed sn-bg-1 custom-scrollbar">

            <!-- Logo -->
            <li>
                <div class="logo-wrapper sn-ad-avatar-wrapper">
                    <img src="https://mdbootstrap.com/images/avatars/img%20(9)" class="img-fluid rounded-circle">
                    <div class="rgba-stylish-strong">
                        <p class="user white-text"><%= current_user.full_name %><br><%= current_user.email %></p>
                    </div>
                </div>
            </li>
            <!--/. Logo -->

            <!-- Side navigation links -->
            <li>
                <ul class="collapsible collapsible-accordion">
                    <li><a class="collapsible-header waves-effect arrow-r active"><i class="fa fa-sitemap"></i> <%= t('.resources') %><i class="fa fa-angle-down rotate-icon"></i></a>
                        <div class="collapsible-body">
                            <ul>
                                <li><%= link_to (admin_routes_path ) do %>
                                <span><i class="fa fa-road"></i> <%= t('.routes') %></span>

                                          <% end %>
                                </li>
                                <li>
                                <%= link_to (admin_railway_stations_path) do %>
                                              <span><i class="fa fa-bank"></i> <%= t('.railway_stations') %></span>
                                          <% end %>
                                </li>
                                <li><%= link_to (admin_trains_path) do %>
                                              <span><i class="fa fa-train ml-auto" data-toggle="tooltip" data-placement="top" title="" data-original-title="Click to fix"></i> <%= t('.trains') %></span>
                                          <% end %>
                                </li>
                                <li>
                                    <%= link_to (admin_tickets_path) do %>
                                              <span><i class="fa fa-ticket"></i> <%= t('.tickets') %></span>
                                          <% end %>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li><a class="collapsible-header waves-effect arrow-r"><i class="fa fa-gitlab"></i> Useful links<i class="fa fa-angle-down rotate-icon"></i></a>
                        <div class="collapsible-body">
                            <ul>
                                <li><a href="https://www.google.com" class="waves-effect" target="_blank" rel="nofollow">Google</a>
                                </li>
                                <li><a href="https://github.com" class="waves-effect" target="_blank" rel="nofollow">GitHub</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </li>
            <!--/. Side navigation links -->
            <div class="sidenav-bg mask-strong"></div>
        </ul>
        <!--/. Sidebar navigation -->

        