config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'searches#show'

  resource :search, only: [:show, :create]

  resources :tickets, only: [:show, :create, :destroy] do
    collection do
      get :my
      post :buy
    end
  end

  namespace :admin do

    resources :railway_stations do
      patch :update_station_place_in_route, on: :member
    end

    resources :routes
    resources :tickets, except: [:new, :create]

    resources :trains do
      resources :carriages, shallow: true
    end

  end 

  

end

app/models/train.rb
class Train < ActiveRecord::Base
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :route
  has_many :tickets
  has_many :carriages

  validates :number, presence: true

  def capacity_by_type(carriage_type, seat_type)
    Carriage.where(type: carriage_type).sum(seat_type) || 0
  end

  def ordered_carriages
    order_from_tail ? carriages.ordered.reverse_order : carriages.ordered
  end
end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end
 
  def edit
  end

  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to admin_train_path(@train), notice: t('.notice')
    else
      render :new
    end
  end

  def update
    if @train.update(train_params)
      redirect_to admin_train_path(@train), notice: t('.notice')
    else
      render :edit
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    redirect_to admin_trains_path, notice: t('.notice')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:number, :current_station_id, :route_id, :order_from_tail)
    end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end
 
  def edit
  end

  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to @train, notice: 'Train was successfully created.'
    else
      render :new
    end
  end

  def update
    if @train.update(train_params)
      redirect_to @train, notice: 'Train was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    redirect_to trains_url, notice: 'Train was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:number, :current_station_id, :route_id, :order_from_tail)
    end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/admin/trains/_form.html.erb
<%= render 'shared/errors_messages', resource: @train %>

<%= form_for [:admin, @train] do |f| %>
    <div class="card">
        <h3 class="card-header primary-color white-text"><i class="fa fa-subway" aria-hidden="true"></i> <%= t('.submit', action: @train.new_record? ? 'Создать' : 'Изменить') %>:</h3>
        <div class="card-block">

            <div class="row">
                <div class="col-md-6">  
                    <h4 class="card-title"><%= t('admin.trains.attributes.number') %>:</h4>
                    <div class="form-group">
                        <%= f.text_field :number %>
                    </div>
                </div>
                <div class="col-md-6">
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <h4 class="card-title"><%= t('admin.trains.attributes.current_station') %>:</h4>
                    <%= f.select :current_station_id, RailwayStation.all.map{ |station| [ "#{station.title}", station.id ] }, {}, class: "mdb-select colorful-select" %>
                </div>
                <div class="col-md-6">
                <h4 class="card-title"><%= t('admin.trains.attributes.route') %>:</h4>
                    <%= f.select :route_id, Route.all.map{ |route| [ "#{route.name}", route.id ] }, {}, class: "mdb-select colorful-select" %>
                </div>
            </div>
            <br />
            <div class="form-group">
                <%= f.check_box :order_from_tail %>
                <%= f.label :order_from_tail %>
            </div>
            <div class="actions">
                <button type="submit" class="btn btn-primary"><%= t('.submit', action: @train.new_record? ? 'Создать' : 'Изменить') %></button>
            </div>
        </div>
    </div>
<% end %>

app/views/admin/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td>
    <% if train.route.present? %>
        <%= link_to train.route.name, admin_route_path(train.route) %>
    <% else %>
        <%= t('shared.not_set.m') %>
    <% end %>
  </td>
  <td>
    <% if train.current_station.present? %>
        <%= link_to train.current_station.title, admin_railway_station_path(train.current_station) %>
    <% else %>
        <%= t('common.not_set.f') %>
    <% end %>
  </td>
  <%= render 'shared/actions', links: {
                  show: admin_train_path(train),
                  edit: edit_admin_train_path(train),
                  delete: admin_train_path(train)
                  } %>
</tr>

app/views/admin/trains/edit.html.erb
<div class="divider-new">
    <h2 class="h2-responsive">
        <%= t('.title') %><strong> <span class="text-muted"></span></strong>
    </h2>
</div>

<%= render 'form' %>

<br />

<%= link_to t('shared.back'), admin_trains_path, class: "text-danger" %> |
<%= link_to t('shared.show'), admin_train_path(@train), class: "text-danger" %>

app/views/admin/trains/index.html.erb
<div class="divider-new">
    <h2 class="h2-responsive">
        <%= t('.title') %><strong> <span class="text-muted"></span></strong>
    </h2>
</div>

<div class="card">
    <h3 class="card-header primary-color white-text"><i class="fa fa-bank" aria-hidden="true"></i> <%= t('.title') %>:</h3>

    <div class="card-block">

        <div class="row">
            <div class="col-md-12">
                 <p class="text-right">
                      <span class=""> <%= link_to t('admin.trains.new.add_new_train'), new_admin_train_path,
                          class: 'btn btn-secondary', role: 'button' %>
                      </span>
                  </p>
            </div>
        </div>

        <table class="table text-center table-hover">
            <thead class="text-center">
                <tr>
                    <th class="text-center"><%= t('admin.trains.attributes.number') %></th>
                    <th class="text-center"><%= t('admin.trains.attributes.route') %></th>
                    <th class="text-center"><%= t('admin.trains.attributes.current_station') %></th>
                    <th class="text-center"><%= t('shared.actions') %></th>
                </tr>
            </thead>

            <tbody>
                <%= render @trains %>
            </tbody>
        </table>
    </div>
</div>

app/views/admin/trains/new.html.erb
<div class="divider-new">
    <h2 class="h2-responsive">
        <%= t('.title') %><strong> <span class="text-muted"></span></strong>
    </h2>
</div>

<%= render 'form' %>

<br />
<%= link_to t('shared.back'), admin_trains_path, class: "text-danger" %>

app/views/admin/trains/show.html.erb
<div class="divider-new">
    <h2 class="h2-responsive">
        <%= t('.title') %><strong> <span class="text-muted">№ <%= @train.number %></span></strong>
    </h2>
</div>

<div class="">
    <p class="text-muted">
        <strong><%= t('admin.trains.attributes.current_station') %>:</strong>
        <% if @train.current_station.present? %>
            <%= link_to @train.current_station.title, admin_railway_station_path(@train.current_station) %>
        <% else %>
            <%= t('shared.not_set.f') %>
        <% end %>
    </p>

    <p class="text-muted">
        <strong><%= t('admin.trains.attributes.route') %>:</strong>
        <% if @train.route.present? %>
            <%= link_to @train.route.name, admin_route_path(@train.route) %>
        <% else %>
            <%= t('shared.not_set.m') %>
        <% end %>
    </p>
</div>

<br />
<div class="card">
    <h3 class="card-header primary-color white-text"><i class="fa fa-subway" aria-hidden="true"></i> <%= t('.carriages') %>:</h3>

    <div class="card-block">
        <p class="text-right">
            <span class=""><%= link_to t('.add_carriage'), new_admin_train_carriage_path(@train),
              class: 'btn btn-secondary', role: 'button' %>
            </span>
        </p>
        <table class="table text-center table-hover">
            <thead class=" text-center">
                <tr>
                    <th class="text-center"><%= t('admin.carriages.attributes.number') %></th>
                    <th class="text-center"><%= t('admin.carriages.attributes.type') %></th>
                    <th class="text-center"><%= t('admin.carriages.show.seats') %></th>
                    <th class="text-center"><%= t('shared.actions') %></th>
                </tr>
            </thead>
            <tbody>
                <% if @train.carriages.empty? %>
                    <tr>
                        <td colspan="4"><h2 class="text-muted"><%= t('shared.empty') %></h2></td>
                    </tr>
                <% else %>
                    <% @train.ordered_carriages.each do |carriage| %>
                        <tr>
                          <td><%= link_to carriage.number, admin_carriage_path(carriage) %></td>
                          <td><%= carriage.type_label %></td>
                          <td><%= render "admin/carriages/seats_#{carriage.type.underscore}", carriage: carriage %></td>
                          <%= render 'shared/actions', links: {
                                      show: admin_carriage_path(carriage),
                                      edit: edit_admin_carriage_path(carriage),
                                      delete: admin_carriage_path(carriage)
                                      } %>
                        </tr>
                    <% end %>
                <% end %>
            </tbody>
        </table>
    </div>
    <h3 class="card-header primary-color white-text"><i class="" aria-hidden="true"></i> <%= t('.seats_count_by_type') %>:</h3>
    <div class="card-block">
        <table class="table text-center table-hover">
            <thead class="text-center">
                <tr>
                    <th class="text-center"><%= t('admin.carriages.attributes.type') %></th>
                    <th class="text-center"><%= t('admin.carriages.attributes.seat_type') %></th>
                    <th class="text-center"><%= t('shared.count') %></th>
                </tr>
            </thead>
            <tbody>
            <% if @train.carriages.empty? %>
                <tr>
                    <td colspan="3"><h2 class="text-muted"><%= t('shared.empty') %></h2></td>
                </tr>
            <% else %>
                <% Carriage::TYPES.each do |carriage_type, carriage_label| %>
                    <% Carriage::SEATS_TYPES.each do |seats_type, seats_label| %>
                        <% count = @train.capacity_by_type(carriage_type, seats_type) %>
                        <% if count > 0 %>
                            <tr>
                                <td><%= carriage_label %></td>
                                <td><%= seats_label %></td>
                                <td><%= count %></td>
                            </tr>
                        <% end %>
                    <% end %>
                <% end %>
            <% end %>
            </tbody>
        </table>
    </div>
</div>

<br />
<%= link_to t('shared.back'), admin_trains_path, class: "text-danger" %> |
<%= link_to t('shared.edit'), edit_admin_train_path(@train), class: "text-danger" %>
<hr>